# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11tLw982ASWjhBHz66caMnFnHG2SndGbT

**1. User Login Check**
"""

# Stored credentials
correct_username = "admin"
correct_password = "1234"

# User input
username = input("Enter username: ")
password = input("Enter password: ")

# Check login
if username == correct_username and password == correct_password:
    print("Login Successful")
else:
    print("Invalid Credentials")

"""**2. Pass / Fail Analyzer**"""

# List of student marks
marks = [45, 78, 90, 33, 60]

# Initialize counters
pass_count = 0
fail_count = 0

# Check each student's marks
for mark in marks:
    if mark >= 50:
        pass_count += 1
    else:
        fail_count += 1

# Print final result
print("Total Students:", len(marks))
print("Number of Students Passed:", pass_count)
print("Number of Students Failed:", fail_count)

"""**3. Simple Data Cleaner**"""

# Original list
names = [" Alice ", "bob", " CHARLIE "]

# Clean names
cleaned_names = []

for name in names:
    cleaned_name = name.strip().lower()
    cleaned_names.append(cleaned_name)

# Print result
print("Original Names:", names)
print("Cleaned Names:", cleaned_names)

"""**4. Message Length Analyzer**"""

# List of messages
messages = ["Hi", "Welcome to the platform", "OK"]

# Loop through each message
for message in messages:
    length = len(message)
    print("Message:", message)
    print("Length:", length)

    if length > 10:
        print("Status: Long message ⚠️")
    else:
        print("Status: Normal message")

    print()  # Blank line for clarity

"""**5. Error Message Detector**"""

# List of system logs
logs = ["INFO", "ERROR", "WARNING", "ERROR"]

# Count number of ERROR entries
error_count = logs.count("ERROR")

print("Total ERROR entries:", error_count)

